on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest 
    env:
      DISPLAY: ':99.0'
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: stable 

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

      - name: Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Test
        run: go test ./...

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests
          path: testoutput/
